# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Moon
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_moon.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
# These custom colors for greater constrast
# https://github.com/gbroques/neovim-configuration/blob/master/lua/plugins/colorscheme.lua#L22-L23k
background = '#1b1d2b'
foreground = '#d3dcf7'

[colors.cursor]
# These custom colors for greater constrast
# https://github.com/gbroques/neovim-configuration/blob/master/lua/plugins/colorscheme.lua#L22-L23k
cursor = '#d3dcf7'
text = '#1b1d2b'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

[font]
size = 22

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[terminal]
shell.program = "/opt/homebrew/bin/fish"
shell.args = ["-C", "cd ~/Projects"]

[window]
startup_mode = "Maximized"

[window.padding]
x = 16
y = 16

